### ISSUE TITLE
Type declaration error

### ISSUE THREAD

**Issue by Kayxue** [YilianSource/pastemyst-ts#2]
When I opened paste.d.ts and I saw this......
![image](https://user-images.githubusercontent.com/26020165/113541051-fd1ccc00-9613-11eb-95f3-d5c1f8272fb7.png)

**Comment by yiliansource** [comment]
Thanks for bringing my attention to this, I forgot that `*.d.ts` aren't picked up by the `tsc` compiler.

This is fixed by updating to v1.0.2.
